
tasks:
  - name: Install AWS CLI
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      # Install AWS CLI v2
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm -rf awscliv2.zip ./aws
      cd $THEIA_WORKSPACE_ROOT

  - name: Install kubectl
    init: |
      # Set Kubernetes version (replace $K8S_VERSION with the actual version or dynamically retrieve it)
      #K8S_VERSION="1.23"  # Example version, replace or dynamically fetch
      echo "Downloading kubectl for Kubernetes version $K8S_VERSION..."
      curl -LO "https://s3.us-west-2.amazonaws.com/amazon-eks/$K8S_VERSION/2023-05-25/bin/linux/amd64/kubectl"
      # Make kubectl executable and move to PATH
      chmod +x kubectl
      sudo mv kubectl /usr/local/bin

      # Verify kubectl installation
      kubectl version --client --short