tasks:
  - name: Install AWS CLI
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      # Install AWS CLI v2
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm -rf awscliv2.zip ./aws
      cd $THEIA_WORKSPACE_ROOT
  - name: Install kubectl CLI
    before: |
      cd /workspace
      # Install kubectl CLI
      mkdir kubectlbinary
      cd kubectlbinary
      echo "Downloading kubectl for Kubernetes version $K8S_VERSION..."
      curl -O "https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.2/2024-11-15/bin/linux/amd64/kubectl"
      # Make kubectl executable and move to PATH
      chmod +x kubectl
      sudo mv kubectl /usr/local/bin
      # Verify kubectl installation
      kubectl version --client
      cd $THEIA_WORKSPACE_ROOT