tasks:
  - name: Install AWS CLI
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      # Install AWS CLI v2
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm -rf awscliv2.zip ./aws
      cd $THEIA_WORKSPACE_ROOT
  - name: Install kubectl CLI & eksctl CLI
    before: |
      cd /workspace
      # Install kubectl CLI
      mkdir kubectlbinary
      cd kubectlbinary
      echo "Downloading kubectl for Kubernetes version $K8S_VERSION..."
      curl -O "https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.2/2024-11-15/bin/linux/amd64/kubectl"
      # Make kubectl executable and move to PATH
      chmod +x kubectl
      sudo mv kubectl /usr/local/bin
      # Verify kubectl installation
      kubectl version --client
      # Install eksctl CLI
      brew install weaveworks/tap/eksctl
      # Verify eksctl installation
      eksctl version      
      cd $THEIA_WORKSPACE_ROOT
  #- name: Install eksctl
  #  before: |
  #    cd /workspace
  #    mkdir eksctlbin
  #    cd eksctlbin
  #    # Install eksctl CLI
  #    echo "Installing eksctl CLI..."
  #    #curl -sL "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" -o eksctl.tar.gz
  #    curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" -o eksctl.tar.gz
  #    tar -xzf eksctl_Linux_amd64.tar.gz -C /usr/local/bin
  #    tar -xzf ksctl_Linux_amd64.tar.gz -C /tmp && rm eksctl_Linux_amd64.tar.gz
  #    #rm eksctl_Linux_amd64.tar.gz
  #
  #    # Verify eksctl installation
  #    eksctl version