tasks:
  - name: Install AWS CLI
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      # Install AWS CLI v2
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm -rf awscliv2.zip ./aws
      cd $THEIA_WORKSPACE_ROOT